"""initalize_entity

Revision ID: 5ec1a5109ef0
Revises: 
Create Date: 2023-01-15 21:58:38.030279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec1a5109ef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_id'), 'box', ['id'], unique=False)
    op.create_table('user_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_grade_id'), 'user_grade', ['id'], unique=False)
    op.create_table('wod_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('level_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wod_level_id'), 'wod_level', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_grade_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('wod_level_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('hashed_pw', sa.String(length=2000), nullable=False),
    sa.Column('cellphone', sa.String(length=50), nullable=True),
    sa.Column('join_type', sa.Enum('KAKAO', 'APPLE', 'EMAIL', name='jointype'), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='gendertype'), nullable=True),
    sa.Column('birth_year', sa.DateTime(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['user_grade_id'], ['user_grade.id'], ),
    sa.ForeignKeyConstraint(['wod_level_id'], ['wod_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('notice_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_category_id'), 'notice_category', ['id'], unique=False)
    op.create_table('wod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('explanation', sa.String(length=255), nullable=True),
    sa.Column('wod_date', sa.DateTime(), nullable=True),
    sa.Column('is_exposed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wod_id'), 'wod', ['id'], unique=False)
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('notice_category_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('is_exposed', sa.Boolean(), nullable=True),
    sa.Column('the_top', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['notice_category_id'], ['notice_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_id'), 'notice', ['id'], unique=False)
    op.create_table('wod_by_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wod_id', sa.Integer(), nullable=False),
    sa.Column('wod_level_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=True),
    sa.Column('record_from_uid', sa.String(length=255), nullable=True),
    sa.Column('ranking_algorithm_uid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['wod_id'], ['wod.id'], ),
    sa.ForeignKeyConstraint(['wod_level_id'], ['wod_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_algorithm_uid'),
    sa.UniqueConstraint('record_from_uid')
    )
    op.create_index(op.f('ix_wod_by_level_id'), 'wod_by_level', ['id'], unique=False)
    op.create_table('wod_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('wod_id', sa.Integer(), nullable=False),
    sa.Column('register', sa.Integer(), nullable=True),
    sa.Column('mango_record_uid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['wod_id'], ['wod.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mango_record_uid')
    )
    op.create_index(op.f('ix_wod_record_id'), 'wod_record', ['id'], unique=False)
    op.create_table('wod_instant_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wod_record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wod_record_id'], ['wod_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wod_instant_team_id'), 'wod_instant_team', ['id'], unique=False)
    op.create_table('wod_ranking_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('wod_id', sa.Integer(), nullable=False),
    sa.Column('wod_record_id', sa.Integer(), nullable=False),
    sa.Column('ranking_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wod_id'], ['wod.id'], ),
    sa.ForeignKeyConstraint(['wod_record_id'], ['wod_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_no')
    )
    op.create_index(op.f('ix_wod_ranking_statistics_id'), 'wod_ranking_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wod_ranking_statistics_id'), table_name='wod_ranking_statistics')
    op.drop_table('wod_ranking_statistics')
    op.drop_index(op.f('ix_wod_instant_team_id'), table_name='wod_instant_team')
    op.drop_table('wod_instant_team')
    op.drop_index(op.f('ix_wod_record_id'), table_name='wod_record')
    op.drop_table('wod_record')
    op.drop_index(op.f('ix_wod_by_level_id'), table_name='wod_by_level')
    op.drop_table('wod_by_level')
    op.drop_index(op.f('ix_notice_id'), table_name='notice')
    op.drop_table('notice')
    op.drop_index(op.f('ix_wod_id'), table_name='wod')
    op.drop_table('wod')
    op.drop_index(op.f('ix_notice_category_id'), table_name='notice_category')
    op.drop_table('notice_category')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_wod_level_id'), table_name='wod_level')
    op.drop_table('wod_level')
    op.drop_index(op.f('ix_user_grade_id'), table_name='user_grade')
    op.drop_table('user_grade')
    op.drop_index(op.f('ix_box_id'), table_name='box')
    op.drop_table('box')
    # ### end Alembic commands ###
